### ISSUE TITLE
client isn't downloading,jar isn't there

### ISSUE THREAD

**Issue by lNethunter** [gingerchicken/como-client#247]

**Comment by gingerchicken** [comment]
I am not sure if I understand your question?

**Comment by lNethunter** [comment]
> I am not sure if I understand your question?

I can't download the client

**Comment by gingerchicken** [comment]
If you're looking for a release/jar to be available then it is not as of yet as I do not feel that my client is at the standard I would like it to be for general/public use.

When it is I will be sure to make a release including jars for the client, however if you're interested in testing it yourself, follow the steps for building the client in the README.

**Comment by gingerchicken** [comment]
But thank you for showing your interest in my client, it really does mean a lot <3

**Comment by lNethunter** [comment]
> But thank you for showing your interest in my client, it really does mean a lot <3

i got no idea how to do all that shi but no prob

**Comment by gingerchicken** [comment]
> > But thank you for showing your interest in my client, it really does mean a lot <3
> 
> i got no idea how to do all that shi but no prob

Out of interest, are you using Windows?  As I should maybe add instructions for being on Windows to my README.

**Comment by lNethunter** [comment]
> > > But thank you for showing your interest in my client, it really does mean a lot <3
> > 
> > 
> > i got no idea how to do all that shi but no prob
> 
> Out of interest, are you using Windows? As I should maybe add instructions for being on Windows to my README.

yes

**Comment by gingerchicken** [comment]
Okay, for future Windows users, I will add some documentation for building the client on Windows.

**Comment by lNethunter** [comment]
> Okay, for future Windows users, I will add some documentation for building the client on Windows.

thank ya
